name: firstapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/delicious-ramen-with-chopsticks.jpg
    - assets/data.json
    - assets/6.jpg
    - assets/10235348.png

  fonts:
    - family: maaja
      fonts:
        - asset: fonts/maaja ver 1.00.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/6.jpg"